/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PasswordRegisterRouteImport } from './routes/passwordRegister'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexDanilaRouteImport } from './routes/indexDanila'
import { Route as IndexRouteImport } from './routes/index'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordRegisterRoute = PasswordRegisterRouteImport.update({
  id: '/passwordRegister',
  path: '/passwordRegister',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexDanilaRoute = IndexDanilaRouteImport.update({
  id: '/indexDanila',
  path: '/indexDanila',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/indexDanila': typeof IndexDanilaRoute
  '/login': typeof LoginRoute
  '/passwordRegister': typeof PasswordRegisterRoute
  '/register': typeof RegisterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/indexDanila': typeof IndexDanilaRoute
  '/login': typeof LoginRoute
  '/passwordRegister': typeof PasswordRegisterRoute
  '/register': typeof RegisterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/indexDanila': typeof IndexDanilaRoute
  '/login': typeof LoginRoute
  '/passwordRegister': typeof PasswordRegisterRoute
  '/register': typeof RegisterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/indexDanila' | '/login' | '/passwordRegister' | '/register'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/indexDanila' | '/login' | '/passwordRegister' | '/register'
  id:
    | '__root__'
    | '/'
    | '/indexDanila'
    | '/login'
    | '/passwordRegister'
    | '/register'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IndexDanilaRoute: typeof IndexDanilaRoute
  LoginRoute: typeof LoginRoute
  PasswordRegisterRoute: typeof PasswordRegisterRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passwordRegister': {
      id: '/passwordRegister'
      path: '/passwordRegister'
      fullPath: '/passwordRegister'
      preLoaderRoute: typeof PasswordRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indexDanila': {
      id: '/indexDanila'
      path: '/indexDanila'
      fullPath: '/indexDanila'
      preLoaderRoute: typeof IndexDanilaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IndexDanilaRoute: IndexDanilaRoute,
  LoginRoute: LoginRoute,
  PasswordRegisterRoute: PasswordRegisterRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
